# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetterToEvent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetterToEvent
  pod 'GoogleMLKit/TextRecognitionKorean', '2.3.0'

  target 'LetterToEventTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetterToEventUITests' do
    # Pods for testing
  end

end
